spring:
  application:
    name: campuscoders-backend
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/campuscoders}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:campus-coders-secret-key-campus-coders-secret-key}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
