spring:
  application:
    name: campuscoders-backend
  datasource:
    url: jdbc:mysql://localhost:3306/campuscoders
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
